# MkDocs Configuration for OmicsOracle

site_name: OmicsOracle Documentation
site_description: AI-Powered Genomics Data Summary Agent
site_author: OmicsOracle Team
site_url: https://omicsoracle.readthedocs.io/

# Repository
repo_name: OmicsOracle/OmicsOracle
repo_url: https://github.com/your-org/OmicsOracle

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - GEO Data Processing: user-guide/geo-processing.md
    - AI Summarization: user-guide/ai-summarization.md
    - API Usage: user-guide/api-usage.md
    - CLI Commands: user-guide/cli-commands.md
  - API Reference:
    - Endpoints: api/endpoints.md
    - Schemas: api/schemas.md
    - Authentication: api/authentication.md
  - Architecture:
    - System Design: architecture/system-design.md
    - Data Flow: architecture/data-flow.md
    - AI Pipeline: architecture/ai-pipeline.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
  - Tutorials:
    - Basic Analysis: tutorials/basic-analysis.md
    - Batch Processing: tutorials/batch-processing.md
    - Custom Workflows: tutorials/custom-workflows.md

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mermaid2

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/OmicsOracle
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/omicsoracle
  version:
    provider: mike
